name: Publish to Replicate

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cog
        run: |
          curl -L https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m) \
            -o ./cog && chmod +x ./cog

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          ./cog login --token $REPLICATE_API_TOKEN
          ./cog push replicate/sh22ppp/43424
